# Generated by Django 5.2.5 on 2025-08-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nrmps", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="interview",
            name="schools_rank_of_student",
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name="interview",
            name="students_rank_of_school",
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name="match",
            name="schools_rank_of_student",
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name="match",
            name="students_rank_of_school",
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name="simulationconfig",
            name="public",
            field=models.BooleanField(default=True),
        ),
    ]
