# Generated by Django 5.2.5 on 2025-09-11 15:25

import nrmps.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nrmps", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simulationconfig",
            name="school_meta_preference",
            field=models.JSONField(
                default=nrmps.models.default_school_meta_preference,
                help_text="List of school preference meta fields (e.g., board_scores, research).",
            ),
        ),
    ]
