# Generated by Django 5.2.5 on 2025-08-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nrmps", "0002_interview_schools_rank_of_student_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="simulationconfig",
            name="description",
        ),
        migrations.RemoveField(
            model_name="simulationconfig",
            name="name",
        ),
        migrations.RemoveField(
            model_name="simulationconfig",
            name="public",
        ),
        migrations.AddField(
            model_name="simulation",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="simulation",
            name="public",
            field=models.BooleanField(default=True),
        ),
    ]
