# Generated by Django 5.2.5 on 2025-09-11 15:29

import nrmps.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nrmps", "0002_alter_simulationconfig_school_meta_preference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simulationconfig",
            name="applicant_meta_preference",
            field=models.JSONField(
                default=nrmps.models.default_applicant_meta_preference,
                help_text="List of applicant preference meta fields (e.g., program_size, prestige).",
            ),
        ),
    ]
