# Generated by Django 5.2.5 on 2025-09-11 15:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nrmps", "0003_alter_simulationconfig_applicant_meta_preference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simulationconfig",
            name="applicant_meta_preference_stddev",
            field=models.FloatField(
                default=3,
                help_text="Std. dev. of meta preference scores (>= 0).",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="simulationconfig",
            name="school_meta_preference_stddev",
            field=models.FloatField(
                default=3, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
