# Generated by Django 5.2.5 on 2025-08-25 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nrmps", "0003_remove_simulationconfig_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="simulation",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="simulations",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
