# Generated by Django 5.2.6 on 2025-09-16 14:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrmps', '0004_alter_simulationconfig_applicant_meta_preference_stddev_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='meta_stddev',
            field=models.FloatField(default=1.0, help_text='Standard deviation of the score.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='school',
            name='meta_stddev_preference',
            field=models.FloatField(default=1.0, help_text='Standard deviation of the preference.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='school',
            name='score',
            field=models.FloatField(help_text='Score of the school.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(0.99)]),
        ),
        migrations.AlterField(
            model_name='simulationconfig',
            name='applicant_meta_preference_stddev',
            field=models.FloatField(default=3, help_text='Std. dev. of meta preference scores (>= 0).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='simulationconfig',
            name='applicant_meta_scores_stddev',
            field=models.FloatField(default=10, help_text='Std. dev. of meta scores per applicant (>= 0).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='simulationconfig',
            name='applicant_post_interview_rating_error',
            field=models.FloatField(default=0.02, help_text='Pre-interview rating error stddev', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(0.99)]),
        ),
        migrations.AlterField(
            model_name='simulationconfig',
            name='applicant_pre_interview_rating_error',
            field=models.FloatField(default=0.1, help_text='Pre-interview rating error stddev', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(0.99)]),
        ),
        migrations.AlterField(
            model_name='simulationconfig',
            name='applicant_score_mean',
            field=models.FloatField(default=0.7, help_text="Mean of the applicants' base scores.", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(0.99)]),
        ),
        migrations.AlterField(
            model_name='simulationconfig',
            name='applicant_score_stddev',
            field=models.FloatField(default=2, help_text="Std. dev. of the applicants' base scores (>= 0).", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='simulationconfig',
            name='school_interview_limit',
            field=models.FloatField(default=0.1, help_text='Max number of interviews each school can conduct In percent of capacity.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(0.99)]),
        ),
        migrations.AlterField(
            model_name='simulationconfig',
            name='school_meta_preference_stddev',
            field=models.FloatField(default=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(0.99)]),
        ),
        migrations.AlterField(
            model_name='simulationconfig',
            name='school_meta_scores_stddev',
            field=models.FloatField(default=2, help_text='Std. dev. of meta scores per school (>= 0).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(0.99)]),
        ),
        migrations.AlterField(
            model_name='simulationconfig',
            name='school_post_interview_rating_error',
            field=models.FloatField(default=0.02, help_text='The stddev scoreing error used to calculate the observed score for each student', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(0.99)]),
        ),
        migrations.AlterField(
            model_name='simulationconfig',
            name='school_pre_interview_rating_error',
            field=models.FloatField(default=0.1, help_text='The stddev scoreing error used to calculate the observed score for each student', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(0.99)]),
        ),
        migrations.AlterField(
            model_name='simulationconfig',
            name='school_score_mean',
            field=models.FloatField(default=0, help_text="Mean of the schools' base scores.", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(0.99)]),
        ),
        migrations.AlterField(
            model_name='simulationconfig',
            name='school_score_stddev',
            field=models.FloatField(default=2, help_text="Std. dev. of the schools' base scores (>= 0).", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
    ]
