# Generated by Django 5.2.5 on 2025-08-26 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nrmps", "0004_simulation_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simulationconfig",
            name="number_of_applicants",
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name="simulationconfig",
            name="number_of_schools",
            field=models.IntegerField(default=10),
        ),
    ]
