# Generated by Django 6.0.2 on 2026-02-21 15:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrmps', '0005_alter_school_meta_stddev_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='status',
            field=models.CharField(choices=[('setup', 'Setup'), ('populations', 'Populations'), ('initialized', 'Initialized'), ('pre_interview', 'Pre-Interview'), ('invitations', 'Invitations'), ('post_interview', 'Post-Interview'), ('final_rankings', 'Final Rankings'), ('matched', 'Matched')], default='setup', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='score',
            field=models.FloatField(help_text='Score of the student.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(0.99)]),
        ),
    ]
