# Generated by Django 5.2.5 on 2025-08-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nrmps", "0005_alter_simulationconfig_number_of_applicants_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="interview",
            old_name="schools_rank_of_student",
            new_name="schools_post_rank_of_student",
        ),
        migrations.RenameField(
            model_name="interview",
            old_name="students_rank_of_school",
            new_name="schools_pre_rank_of_student",
        ),
        migrations.AddField(
            model_name="interview",
            name="school_post_observed_score_of_student",
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name="interview",
            name="school_pre_observed_score_of_student",
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name="interview",
            name="student_post_observed_score_of_school",
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name="interview",
            name="student_pre_observed_score_of_school",
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name="interview",
            name="students_post_rank_of_school",
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name="interview",
            name="students_pre_rank_of_school",
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name="simulationconfig",
            name="applicant_score_meta",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="student",
            name="schools_signaled",
            field=models.JSONField(default=list),
        ),
    ]
