# Generated by Django 6.0.2 on 2026-02-21 15:36

from django.db import migrations


def convert_pending_to_stage(apps, schema_editor):
    """Convert existing 'pending' status to the appropriate pipeline stage."""
    Simulation = apps.get_model("nrmps", "Simulation")
    Interview = apps.get_model("nrmps", "Interview")

    for sim in Simulation.objects.all():
        if sim.status not in ("pending", ""):
            continue
        # Determine stage from data
        has_students = sim.students.exists()
        has_schools = sim.schools.exists()
        has_interviews = Interview.objects.filter(simulation=sim).exists()
        has_pre_scores = Interview.objects.filter(
            simulation=sim, student_pre_observed_score_of_school__isnull=False
        ).exists()
        has_post_scores = Interview.objects.filter(
            simulation=sim, student_post_observed_score_of_school__isnull=False
        ).exists()

        if has_post_scores:
            sim.status = "post_interview"
        elif has_pre_scores:
            sim.status = "pre_interview"
        elif has_interviews:
            sim.status = "initialized"
        elif has_students and has_schools:
            sim.status = "populations"
        else:
            sim.status = "setup"
        sim.save(update_fields=["status"])


class Migration(migrations.Migration):

    dependencies = [
        ("nrmps", "0006_alter_simulation_status_alter_student_score"),
    ]

    operations = [
        migrations.RunPython(convert_pending_to_stage, migrations.RunPython.noop),
    ]
