# Generated by Django 5.2.5 on 2025-08-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "nrmps",
            "0006_rename_schools_rank_of_student_interview_schools_post_rank_of_student_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="interview",
            name="school_accepted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="interview",
            name="school_invited",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="interview",
            name="student_accepted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="interview",
            name="student_applied",
            field=models.BooleanField(default=False),
        ),
    ]
