# Generated by Django 6.1.1 on 2026-09-26 02:18

import django.core.validators
import nrmps.models
from django.db import migrations, models


def make_existing_simulations_private(apps, schema_editor):
    """Set public=False on every existing simulation.

    The flag defaulted to True and was pre-checked on the form, but nothing read it, so no owner meaningfully chose
    to publish. Sharing features built later must start from private simulations (review finding CRIT-3).
    """
    Simulation = apps.get_model("nrmps", "Simulation")
    Simulation.objects.filter(public=True).update(public=False)


class Migration(migrations.Migration):
    dependencies = [
        ("nrmps", "0007_convert_pending_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interview",
            name="school_invited",
            field=models.BooleanField(
                default=False,
                help_text="True if the program invited this applicant to interview (requires an application).",
            ),
        ),
        migrations.AlterField(
            model_name="interview",
            name="school_post_observed_score_of_student",
            field=models.FloatField(
                blank=True, help_text="Program's post-interview rating of this applicant.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="interview",
            name="school_pre_observed_score_of_student",
            field=models.FloatField(
                blank=True, help_text="Program's pre-interview (noisy) rating of this applicant.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="interview",
            name="school_true_score_of_student",
            field=models.FloatField(
                blank=True,
                help_text="Program's noise-free utility for this applicant (sum of weight x applicant attribute).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="interview",
            name="schools_post_rank_of_student",
            field=models.IntegerField(
                blank=True, help_text="Where this applicant falls in the program's post-interview ordering.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="interview",
            name="schools_pre_rank_of_student",
            field=models.IntegerField(
                blank=True,
                help_text="Where this applicant falls in the program's pre-interview ordering (1 = top applicant).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="interview",
            name="status",
            field=models.CharField(
                default="initialized",
                help_text="Stage reached for this pair (currently always initialized).",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="interview",
            name="student_accepted",
            field=models.BooleanField(
                default=False, help_text="True if the applicant accepted this program's interview invitation."
            ),
        ),
        migrations.AlterField(
            model_name="interview",
            name="student_applied",
            field=models.BooleanField(default=False, help_text="True if the applicant applied to this program."),
        ),
        migrations.AlterField(
            model_name="interview",
            name="student_post_observed_score_of_school",
            field=models.FloatField(
                blank=True, help_text="Applicant's post-interview rating of this program.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="interview",
            name="student_pre_observed_score_of_school",
            field=models.FloatField(
                blank=True, help_text="Applicant's pre-interview (noisy) rating of this program.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="interview",
            name="student_signal",
            field=models.IntegerField(
                default=0, help_text="Preference signal the applicant sent this program (0 = none). Not used yet."
            ),
        ),
        migrations.AlterField(
            model_name="interview",
            name="student_true_score_of_school",
            field=models.FloatField(
                blank=True,
                help_text="Applicant's noise-free utility for this program (sum of weight x program attribute).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="interview",
            name="students_post_rank_of_school",
            field=models.IntegerField(
                blank=True, help_text="Where this program falls in the applicant's post-interview ordering.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="interview",
            name="students_pre_rank_of_school",
            field=models.IntegerField(
                blank=True,
                help_text="Where this program falls in the applicant's pre-interview ordering (1 = favourite).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="school",
            name="capacity",
            field=models.IntegerField(help_text="Number of positions the program can fill (>= 0)."),
        ),
        migrations.AlterField(
            model_name="school",
            name="meta_preference",
            field=models.JSONField(
                default=dict,
                help_text='Program preference weights (sum to 1) keyed by the applicant attributes programs value, e.g. {"board_scores": 0.5, "research": 0.3, "honors": 0.2}.',
            ),
        ),
        migrations.AlterField(
            model_name="school",
            name="meta_stddev_preference",
            field=models.FloatField(
                default=1.0,
                help_text="SD used when this program's preference weights were drawn (copied from config).",
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)],
            ),
        ),
        migrations.AlterField(
            model_name="school",
            name="name",
            field=models.CharField(help_text="Program name.", max_length=255),
        ),
        migrations.AlterField(
            model_name="school",
            name="score",
            field=models.FloatField(
                help_text="Program's base (true overall) quality, 0-1; centre of its attribute scores.",
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1.0)],
            ),
        ),
        migrations.AlterField(
            model_name="school",
            name="score_meta",
            field=models.JSONField(
                default=dict,
                help_text='Program attribute scores (0-1) keyed by the attributes applicants value, e.g. {"program_size": 0.4, "reputation": 0.8, "location": 0.6}.',
            ),
        ),
        migrations.AlterField(
            model_name="simulation",
            name="description",
            field=models.TextField(blank=True, default="", help_text="Notes on what you are testing (optional)."),
        ),
        migrations.AlterField(
            model_name="simulation",
            name="iterations",
            field=models.IntegerField(
                default=1,
                help_text="Planned: number of independent repeats with different random seeds; results will be aggregated. Not used yet.",
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)],
            ),
        ),
        migrations.AlterField(
            model_name="simulation",
            name="name",
            field=models.CharField(help_text="A short name for this experiment.", max_length=255),
        ),
        migrations.AlterField(
            model_name="simulation",
            name="public",
            field=models.BooleanField(
                default=False,
                help_text="Planned: let others view this simulation read-only. Currently has no effect; only you can see it.",
            ),
        ),
        migrations.AlterField(
            model_name="simulationconfig",
            name="applicant_interview_limit",
            field=models.IntegerField(
                default=5,
                help_text="Not used yet: the most interviews an applicant can accept and attend.",
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)],
            ),
        ),
        migrations.AlterField(
            model_name="simulationconfig",
            name="applicant_meta_preference",
            field=models.JSONField(
                default=nrmps.models.default_applicant_meta_preference,
                help_text="Program attributes applicants care about, e.g. program_size, reputation, location.",
            ),
        ),
        migrations.AlterField(
            model_name="simulationconfig",
            name="applicant_meta_preference_stddev",
            field=models.FloatField(
                default=0.3,
                help_text="How much applicants disagree about which program attributes matter.",
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1.0)],
            ),
        ),
        migrations.AlterField(
            model_name="simulationconfig",
            name="applicant_meta_scores_stddev",
            field=models.FloatField(
                default=0.1,
                help_text="How much an applicant's attribute scores vary around their base score.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(0.45),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="simulationconfig",
            name="applicant_post_interview_rating_error",
            field=models.FloatField(
                default=0.02,
                help_text="Not used yet: how noisy applicants' view of programs is after interviewing.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(0.99),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="simulationconfig",
            name="applicant_pre_interview_rating_error",
            field=models.FloatField(
                default=0.1,
                help_text="How noisy applicants' view of programs is before interviewing (0 = perfect information).",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(0.99),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="simulationconfig",
            name="applicant_score_mean",
            field=models.FloatField(
                default=0.7,
                help_text="Average applicant base (overall strength) score on a 0-1 scale.",
                validators=[
                    django.core.validators.MinValueValidator(0.01),
                    django.core.validators.MaxValueValidator(0.99),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="simulationconfig",
            name="applicant_score_stddev",
            field=models.FloatField(
                default=0.1,
                help_text="How spread out applicant base scores are (SD on the 0-1 scale).",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(0.45),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="simulationconfig",
            name="number_of_applicants",
            field=models.IntegerField(
                default=200,
                help_text="How many applicants (medical students) to generate.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="simulationconfig",
            name="number_of_schools",
            field=models.IntegerField(
                default=10,
                help_text="How many residency programs to generate.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(1000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="simulationconfig",
            name="school_capacity_mean",
            field=models.FloatField(
                default=20,
                help_text="Average number of residency positions per program.",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="simulationconfig",
            name="school_capacity_stddev",
            field=models.FloatField(
                default=4,
                help_text="How much program sizes vary (at most half the mean is recommended).",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="simulationconfig",
            name="school_interview_limit",
            field=models.FloatField(
                default=0.1,
                help_text="Not used yet: Phase 2 replaces it with interviews per position.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(0.99),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="simulationconfig",
            name="school_meta_preference",
            field=models.JSONField(
                default=nrmps.models.default_school_meta_preference,
                help_text="Applicant attributes programs care about, e.g. board_scores, research, honors.",
            ),
        ),
        migrations.AlterField(
            model_name="simulationconfig",
            name="school_meta_preference_stddev",
            field=models.FloatField(
                default=0.3,
                help_text="How much programs disagree about which applicant attributes matter.",
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1.0)],
            ),
        ),
        migrations.AlterField(
            model_name="simulationconfig",
            name="school_meta_scores_stddev",
            field=models.FloatField(
                default=0.1,
                help_text="How much a program's attribute scores vary around its base score.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(0.45),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="simulationconfig",
            name="school_post_interview_rating_error",
            field=models.FloatField(
                default=0.02,
                help_text="Not used yet: how noisy programs' view of applicants is after interviewing.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(0.99),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="simulationconfig",
            name="school_pre_interview_rating_error",
            field=models.FloatField(
                default=0.1,
                help_text="How noisy programs' view of applicants is from the application alone (0 = perfect information).",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(0.99),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="simulationconfig",
            name="school_score_mean",
            field=models.FloatField(
                default=0.5,
                help_text="Average program base (overall quality) score on a 0-1 scale.",
                validators=[
                    django.core.validators.MinValueValidator(0.01),
                    django.core.validators.MaxValueValidator(0.99),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="simulationconfig",
            name="school_score_stddev",
            field=models.FloatField(
                default=0.1,
                help_text="How spread out program base scores are (SD on the 0-1 scale).",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(0.45),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="meta_preference",
            field=models.JSONField(
                default=dict,
                help_text='Applicant preference weights (sum to 1) keyed by the program attributes applicants value, e.g. {"program_size": 0.31, "reputation": 0.45, "location": 0.24}.',
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="meta_stddev_preference",
            field=models.FloatField(
                default=0.0,
                help_text="SD used when this applicant's preference weights were drawn (copied from config).",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="name",
            field=models.CharField(help_text="Applicant name.", max_length=255),
        ),
        migrations.AlterField(
            model_name="student",
            name="score",
            field=models.FloatField(
                help_text="Applicant's base (true overall) strength, 0-1; centre of their attribute scores.",
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1.0)],
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="score_meta",
            field=models.JSONField(
                default=dict,
                help_text='Applicant attribute scores (0-1) keyed by the attributes programs value, e.g. {"board_scores": 0.72, "research": 0.55, "honors": 0.61}.',
            ),
        ),
        migrations.RunPython(make_existing_simulations_private, migrations.RunPython.noop),
    ]
