# Generated by Django 5.2.5 on 2025-08-28 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nrmps", "0007_interview_school_accepted_interview_school_invited_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="schools_signaled",
        ),
    ]
