# Generated by Django 5.2.5 on 2025-08-31 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nrmps", "0008_remove_student_schools_signaled"),
    ]

    operations = [
        migrations.AddField(
            model_name="interview",
            name="student_signal",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="school",
            name="meta_stddev",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="school",
            name="score_meta",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="simulationconfig",
            name="applicant_meta_preference",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="simulationconfig",
            name="applicant_meta_scores",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="simulationconfig",
            name="school_meta_preference",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="simulationconfig",
            name="school_meta_scores",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="student",
            name="meta_stddev",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="student",
            name="score_meta",
            field=models.JSONField(default=dict),
        ),
    ]
