# Generated by Django 6.1.1 on 2026-09-26 02:38

import nrmps.models
import nrmps.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrmps', '0008_interim_defaults_and_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulationconfig',
            name='applicant_meta_preference',
            field=models.JSONField(default=nrmps.models.default_applicant_meta_preference, help_text='Program attributes applicants care about, e.g. program_size, reputation, location.', validators=[nrmps.validators.validate_attribute_list]),
        ),
        migrations.AlterField(
            model_name='simulationconfig',
            name='school_meta_preference',
            field=models.JSONField(default=nrmps.models.default_school_meta_preference, help_text='Applicant attributes programs care about, e.g. board_scores, research, honors.', validators=[nrmps.validators.validate_attribute_list]),
        ),
    ]
