# Generated by Django 6.1.1 on 2026-09-26 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrmps', '0009_validate_attribute_lists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
