# Generated by Django 5.2.5 on 2025-08-31 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nrmps", "0009_interview_student_signal_school_meta_stddev_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="simulationconfig",
            old_name="applicants_interview_limit",
            new_name="applicant_interview_limit",
        ),
        migrations.RenameField(
            model_name="simulationconfig",
            old_name="applicants_score_mean",
            new_name="applicant_score_mean",
        ),
        migrations.RenameField(
            model_name="simulationconfig",
            old_name="schools_score_mean",
            new_name="school_score_mean",
        ),
        migrations.RenameField(
            model_name="simulationconfig",
            old_name="schools_score_stddev",
            new_name="school_score_stddev",
        ),
    ]
