# Generated by Django 5.2.5 on 2025-08-31 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "nrmps",
            "0010_rename_applicants_interview_limit_simulationconfig_applicant_interview_limit_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="simulationconfig",
            name="applicant_score_meta",
        ),
    ]
