# Generated by Django 6.1.1 on 2026-09-26 03:31

import django.db.models.functions.text
from django.db import migrations, models


def clear_duplicate_emails(apps, schema_editor):
    """Keep each email address (ignoring case) on its oldest account only; clear it on newer ones.

    The unique constraint added next would otherwise fail on existing duplicates. Affected accounts keep working and
    can add a new address on their account page.
    """
    User = apps.get_model("nrmps", "User")
    seen = set()
    for user in User.objects.exclude(email="").order_by("id"):
        key = user.email.lower()
        if key in seen:
            user.email = ""
            user.save(update_fields=["email"])
        else:
            seen.add(key)


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('nrmps', '0010_user_full_name_not_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, help_text='When the current email address was confirmed (empty: not confirmed).', null=True),
        ),
        migrations.RunPython(clear_duplicate_emails, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), condition=models.Q(('email', ''), _negated=True), name='unique_user_email_ignoring_case'),
        ),
    ]
