# Generated by Django 5.2.5 on 2025-08-31 13:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nrmps", "0011_remove_simulationconfig_applicant_score_meta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simulationconfig",
            name="applicant_interview_limit",
            field=models.FloatField(
                default=5,
                help_text="Max number of interviews each applicant can attend.",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="simulationconfig",
            name="applicant_meta_preference",
            field=models.JSONField(
                default=list,
                help_text="List of applicant preference meta fields (e.g., program_size, prestige).",
            ),
        ),
        migrations.AlterField(
            model_name="simulationconfig",
            name="applicant_meta_scores",
            field=models.JSONField(
                default=list,
                help_text="List of meta-score names for applicants (e.g., research, leadership).",
            ),
        ),
        migrations.AlterField(
            model_name="simulationconfig",
            name="applicant_score_mean",
            field=models.FloatField(
                default=0,
                help_text="Mean of the applicants' base scores.",
                validators=[
                    django.core.validators.MinValueValidator(-1000),
                    django.core.validators.MaxValueValidator(1000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="simulationconfig",
            name="applicant_score_stddev",
            field=models.FloatField(
                default=25,
                help_text="Std. dev. of the applicants' base scores (>= 0).",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="simulationconfig",
            name="number_of_applicants",
            field=models.IntegerField(
                default=200,
                help_text="Total number of applicants to generate.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="simulationconfig",
            name="number_of_schools",
            field=models.IntegerField(
                default=10,
                help_text="Total number of schools to generate.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(1000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="simulationconfig",
            name="school_capacity_mean",
            field=models.FloatField(default=20, help_text="Mean capacity per school."),
        ),
        migrations.AlterField(
            model_name="simulationconfig",
            name="school_capacity_stddev",
            field=models.FloatField(
                default=10,
                help_text="Std. dev. of capacity per school (>= 0).",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="simulationconfig",
            name="school_interview_limit",
            field=models.FloatField(
                default=10,
                help_text="Max number of interviews each school can conduct.",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="simulationconfig",
            name="school_meta_preference",
            field=models.JSONField(
                default=list,
                help_text="List of school preference meta fields (e.g., board_scores, research).",
            ),
        ),
        migrations.AlterField(
            model_name="simulationconfig",
            name="school_meta_scores",
            field=models.JSONField(
                default=list,
                help_text="List of meta-score names for schools (e.g., research_strength, teaching).",
            ),
        ),
        migrations.AlterField(
            model_name="simulationconfig",
            name="school_score_mean",
            field=models.FloatField(
                default=0,
                help_text="Mean of the schools' base scores.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(1000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="simulationconfig",
            name="school_score_stddev",
            field=models.FloatField(
                default=25,
                help_text="Std. dev. of the schools' base scores (>= 0).",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
