# Generated by Django 6.1.1 on 2026-09-26 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nrmps', '0011_user_email_verification_and_unique_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': 'program'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'applicant'},
        ),
        migrations.RemoveField(
            model_name='school',
            name='meta_stddev',
        ),
        migrations.RemoveField(
            model_name='student',
            name='meta_stddev',
        ),
        migrations.RemoveField(
            model_name='user',
            name='disabled',
        ),
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
    ]
