# Generated by Django 5.2.5 on 2025-08-31 15:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nrmps", "0012_alter_simulationconfig_applicant_interview_limit_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interview",
            name="school_accepted",
        ),
        migrations.AlterField(
            model_name="interview",
            name="school_invited",
            field=models.BooleanField(
                default=False,
                help_text="Whether the school has been invited to the interview. Must have applied to school first",
            ),
        ),
        migrations.AlterField(
            model_name="interview",
            name="school_post_observed_score_of_student",
            field=models.FloatField(
                default=None, help_text='Post interview "total" score of school'
            ),
        ),
        migrations.AlterField(
            model_name="interview",
            name="school_pre_observed_score_of_student",
            field=models.FloatField(
                default=None, help_text='Pre interview "total" score of school'
            ),
        ),
        migrations.AlterField(
            model_name="interview",
            name="schools_post_rank_of_student",
            field=models.IntegerField(
                default=None, help_text="Post interview rank of school"
            ),
        ),
        migrations.AlterField(
            model_name="interview",
            name="schools_pre_rank_of_student",
            field=models.IntegerField(
                default=None, help_text="Pre interview rank of school"
            ),
        ),
        migrations.AlterField(
            model_name="interview",
            name="student_accepted",
            field=models.BooleanField(
                default=False,
                help_text="Whether the student has been accepted to the school invitation to interview.",
            ),
        ),
        migrations.AlterField(
            model_name="interview",
            name="student_applied",
            field=models.BooleanField(
                default=False,
                help_text="Whether the student has been applied to the school.",
            ),
        ),
        migrations.AlterField(
            model_name="interview",
            name="student_post_observed_score_of_school",
            field=models.FloatField(
                default=None, help_text='Post interview "total score" of student'
            ),
        ),
        migrations.AlterField(
            model_name="interview",
            name="student_pre_observed_score_of_school",
            field=models.FloatField(
                default=None, help_text='Pre interview "total" score of student'
            ),
        ),
        migrations.AlterField(
            model_name="interview",
            name="student_signal",
            field=models.IntegerField(
                default=0, help_text="Signal value from the student to the school"
            ),
        ),
        migrations.AlterField(
            model_name="interview",
            name="students_post_rank_of_school",
            field=models.IntegerField(
                default=None, help_text="Post interview rank of student"
            ),
        ),
        migrations.AlterField(
            model_name="interview",
            name="students_pre_rank_of_school",
            field=models.IntegerField(
                default=None, help_text="Pre interview rank of student"
            ),
        ),
        migrations.AlterField(
            model_name="simulationconfig",
            name="school_score_mean",
            field=models.FloatField(
                default=0,
                help_text="Mean of the schools' base scores.",
                validators=[
                    django.core.validators.MinValueValidator(-1000),
                    django.core.validators.MaxValueValidator(1000),
                ],
            ),
        ),
    ]
