# Generated by Django 5.2.5 on 2025-09-01 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nrmps", "0013_remove_interview_school_accepted_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="simulationconfig",
            name="applicant_meta_scores",
        ),
    ]
