# Generated by Django 5.2.5 on 2025-09-01 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nrmps", "0014_remove_simulationconfig_applicant_meta_scores"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="simulationconfig",
            name="school_meta_scores",
        ),
    ]
