# Generated by Django 5.2.5 on 2025-09-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nrmps", "0015_remove_simulationconfig_school_meta_scores"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="capacity",
            field=models.IntegerField(help_text="Capacity of the school."),
        ),
        migrations.AlterField(
            model_name="school",
            name="meta_stddev",
            field=models.FloatField(
                default=0.0, help_text="Standard deviation of the score."
            ),
        ),
        migrations.AlterField(
            model_name="school",
            name="name",
            field=models.CharField(help_text="Name of the school.", max_length=255),
        ),
        migrations.AlterField(
            model_name="school",
            name="score",
            field=models.FloatField(help_text="Score of the school."),
        ),
        migrations.AlterField(
            model_name="school",
            name="score_meta",
            field=models.JSONField(
                default=dict,
                help_text='Meta score names and value {"Research":5, "Reputation": 10} for the score.',
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="meta_stddev",
            field=models.FloatField(
                default=0.0, help_text="Standard deviation of the score."
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="name",
            field=models.CharField(help_text="Name of the student.", max_length=255),
        ),
        migrations.AlterField(
            model_name="student",
            name="score",
            field=models.FloatField(help_text="Score of the student."),
        ),
        migrations.AlterField(
            model_name="student",
            name="score_meta",
            field=models.JSONField(
                default=dict,
                help_text='Meta score names and value {"USMLE Setp 2":5, "Grades": 10} for the score.',
            ),
        ),
    ]
