# Generated by Django 6.1.1 on 2026-09-26 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrmps', '0015_runs_replace_legacy_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_id', models.CharField(max_length=64, unique=True)),
                ('hostname', models.CharField(blank=True, default='', max_length=255)),
                ('started_at', models.DateTimeField()),
                ('last_seen', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='simulationrun',
            name='notify_email',
            field=models.BooleanField(default=False, help_text='Email the owner when the run finishes.'),
        ),
        migrations.CreateModel(
            name='RateLimitCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('window_start', models.DateTimeField()),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['window_start'], name='rate_limit_window')],
                'constraints': [models.UniqueConstraint(fields=('key', 'window_start'), name='unique_rate_limit_window')],
            },
        ),
    ]
