# Generated by Django 5.2.5 on 2025-09-01 15:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nrmps", "0016_alter_school_capacity_alter_school_meta_stddev_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="simulationconfig",
            name="applicant_meta_preference_stddev",
            field=models.FloatField(
                default=10,
                help_text="Std. dev. of meta preference scores (>= 0).",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="simulationconfig",
            name="applicant_meta_scores_stddev",
            field=models.FloatField(
                default=10,
                help_text="Std. dev. of meta scores per applicant (>= 0).",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="simulationconfig",
            name="school_meta_preference_stddev",
            field=models.FloatField(
                default=10, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="simulationconfig",
            name="school_meta_scores_stddev",
            field=models.FloatField(
                default=10,
                help_text="Std. dev. of meta scores per school (>= 0).",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="simulationconfig",
            name="applicant_interview_limit",
            field=models.IntegerField(
                default=5,
                help_text="Max number of interviews each applicant can attend.",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="simulationconfig",
            name="school_interview_limit",
            field=models.FloatField(
                default=10,
                help_text="Max number of interviews each school can conduct Inpercent of capacity.",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
