# Generated by Django 6.1.1 on 2026-09-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrmps', '0016_background_runs_and_limits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runartifact',
            name='kind',
            field=models.CharField(choices=[('population', 'Population'), ('pre_interview', 'Pre-interview results'), ('stages', 'Applications to the match')], max_length=30),
        ),
    ]
