# Generated by Django 6.1.1 on 2026-09-26 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrmps', '0017_stage_artifacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The preset's name, unique among the user's presets.", max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('params', models.JSONField(help_text='The parameters (SimulationParams JSON) without the seed.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'name'), name='unique_preset_name_per_owner')],
            },
        ),
    ]
