"""Admin site registrations.

Users, simulations and configurations can be edited. Populations, interview rows and matches are generated by the
engine, so staff can view and delete them but not add or change them.
"""

from django.contrib import admin
from django.contrib.auth.admin import UserAdmin as DjangoUserAdmin

from .models import Interview, Match, School, Simulation, SimulationConfig, Student, User


@admin.register(User)
class UserAdmin(DjangoUserAdmin):
    """The custom user, with its full name."""

    fieldsets = (*(DjangoUserAdmin.fieldsets or ()), ("Profile", {"fields": ("full_name",)}))
    list_display = ("username", "email", "full_name", "is_staff", "is_active", "date_joined")


class SimulationConfigInline(admin.StackedInline):
    """A simulation's configurations (the latest one is used)."""

    model = SimulationConfig
    extra = 0
    show_change_link = True


@admin.register(Simulation)
class SimulationAdmin(admin.ModelAdmin):
    """Simulations with their owner, stage and population sizes."""

    list_display = ("name", "owner", "status", "n_students", "n_schools", "created_at")
    list_filter = ("status", "public")
    search_fields = ("name", "owner__username")
    list_select_related = ("owner",)
    inlines = (SimulationConfigInline,)

    def get_queryset(self, request):
        """Annotate the population sizes (one subquery each)."""
        return super().get_queryset(request).with_counts()

    @admin.display(description="Students", ordering="n_students")
    def n_students(self, obj) -> int:
        """Return the number of students."""
        return obj.n_students

    @admin.display(description="Schools", ordering="n_schools")
    def n_schools(self, obj) -> int:
        """Return the number of schools."""
        return obj.n_schools


@admin.register(SimulationConfig)
class SimulationConfigAdmin(admin.ModelAdmin):
    """Configurations, editable."""

    list_display = ("simulation", "number_of_applicants", "number_of_schools")
    list_select_related = ("simulation",)
    search_fields = ("simulation__name",)


class GeneratedRowAdmin(admin.ModelAdmin):
    """Rows the engine generates: viewable and deletable, not editable. No full counts on large tables."""

    show_full_result_count = False
    list_per_page = 100

    def has_add_permission(self, request) -> bool:
        """Generated rows are not added by hand."""
        return False

    def has_change_permission(self, request, obj=None) -> bool:
        """Generated rows are not edited by hand."""
        return False


@admin.register(Student)
class StudentAdmin(GeneratedRowAdmin):
    """Students (applicants)."""

    list_display = ("name", "simulation", "score")
    list_select_related = ("simulation",)
    search_fields = ("name", "simulation__name")


@admin.register(School)
class SchoolAdmin(GeneratedRowAdmin):
    """Schools (programs)."""

    list_display = ("name", "simulation", "capacity", "score")
    list_select_related = ("simulation",)
    search_fields = ("name", "simulation__name")


@admin.register(Interview)
class InterviewAdmin(GeneratedRowAdmin):
    """Interview rows: one per student and school pair."""

    list_display = (
        "student",
        "school",
        "simulation",
        "status",
        "students_pre_rank_of_school",
        "schools_pre_rank_of_student",
    )
    list_select_related = ("student", "school", "simulation")
    list_filter = ("status",)
    raw_id_fields = ("simulation", "student", "school")


@admin.register(Match)
class MatchAdmin(GeneratedRowAdmin):
    """Match results (not produced yet)."""

    list_display = ("student", "school", "simulation")
    list_select_related = ("student", "school", "simulation")
    raw_id_fields = ("simulation", "student", "school")
